version: "3.10"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=asiyakhan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=soundBook
  server:
    build: ./backend
    ports: 
    - "80:5000"
    volumes:
    - ./backend:/app/
    environment:
      FLASK_ENV: development
    depends_on:
      - db
  web:
    build: ./frontend/
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/app/
    depends_on:
      - server
volumes:
  postgres_data:
